"""sweep_selective.py -- the analyses added by the SELECTIVE-PRESENTATION round.

A new error species was identified: computing several parallel analyses and
printing only the favourable one, or quoting a series at its most favourable
point.  This script archives, in full, every series and every parallel variant
the paper quotes from:

  E1  the by-question THREE-FAMILY split, all three families printed with their
      K, their survivor counts and their member cells -- Sec. 4.9 previously
      printed only the route-comparison family, the one containing the title;
  E2  both long-budget (n=3) plateau series in full, 12k -> 32k, so that no
      single checkpoint of either can be quoted as if it were a trend;
  E3  both clean-teacher TRAINING curves, the fact that the saved checkpoint is
      a terminal save off a violently non-monotone curve with no model
      selection, and the 12k checkpoints of the same two runs -- which exist on
      disk (`teacher_*_clean12k.pt`) and had never been scored;
  E4  the FOURTH long-budget unaided run per body: `train_teacher2.py` runs
      `blank` seed 100 for 30,000 steps and `teacher_eval.py` scores it on the
      same 20 held-out targets `--heldout` uses, so the teacher run is also an
      unaided long-budget baseline;
  E5  the sweep register: every number the paper quotes from a series, checked
      against that series for a favourable extremum.

Written by APPENDING to RECOMPUTED.md.  This script never opens that file in
write mode and never truncates it.  Running it twice is a no-op.

Usage:  python sweep_selective.py            # print only
        python sweep_selective.py --append   # print and append to RECOMPUTED.md
"""

import os
import re
import sys

import movement_index_holm72 as H

ROOT = os.path.dirname(os.path.abspath(__file__))
REC_PATH = os.path.join(ROOT, "RECOMPUTED.md")
MARKER = ("# Appendix E — the by-question family splits in full, both long-budget "
          "series, and the teacher checkpoint curves")

STEP_RE = re.compile(r"step\s+(\d+)\s+eval_ret\s+(-?[\d.]+)\s+dist\s+([\d.]+)mm")


def curve(path):
    """step -> eval distance (x1000: mrad on elbow, mm on finger)."""
    out = {}
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = STEP_RE.search(line)
            if m:
                out[int(m.group(1))] = float(m.group(3))
    return out


def plateau(body):
    d = os.path.join(ROOT, "results_plateau2_%s" % body)
    B = [curve(os.path.join(d, "blank_s%d.log" % s)) for s in (0, 1, 2)]
    P = [curve(os.path.join(d, "prior_s%d.log" % s)) for s in (0, 1, 2)]
    return B, P


def mean_at(series, step):
    v = [s[step] for s in series if step in s]
    return (sum(v) / len(v), len(v)) if v else (None, 0)


# --------------------------------------------------------------------- E3 data
# `teacher_eval.py` transcripts.  The 30k rows are the archived ones the paper
# already quotes; the 12k rows were produced by running the SAME script on the
# `*_clean12k.pt` checkpoints, which had been on disk unscored since 27 July.
TEACHER_EVAL = [
    # body, checkpoint, train, held-out
    ("myoElbow",  "teacher_elbow_clean12k.pt",   47.7,  62.6),
    ("myoElbow",  "teacher_elbow_clean30k.pt",   15.5,  27.2),
    ("myoFinger", "teacher_finger_clean12k.pt", 134.0, 129.4),
    ("myoFinger", "teacher_finger_clean30k.pt", 133.5, 169.1),
]


def render():
    L = []
    A = L.append
    A("")
    A("---")
    A("")
    A(MARKER)
    A("")
    A("_Generated by `sweep_selective.py` (appended, never rewritten). This appendix exists "
      "because a new error species was identified: **selective presentation** — computing "
      "several parallel analyses and printing only the favourable one, or quoting a series at "
      "its most favourable point. Everything below is printed in full for that reason._")
    A("")

    # ================================================================== E1
    cells = H.build_cells()
    A("## E1. The by-question three-family split, all three families printed")
    A("")
    A("D2d reported the three families' **counts** but Sec. 4.9's prose quoted only the "
      "route-comparison family — the one containing the title's cell. All three are printed "
      "here with their members, because applying a family definition at the site where it "
      "rescues the title and nowhere else is one-sided in the raising direction.")
    A("")
    fam_summary = []
    for nm, keys, q in (("route comparison", H.ROUTE, "which aid is faster / which leads"),
                        ("versus model-free", H.BEATS, "does either beat model-free RL"),
                        ("removal", H.REMOVAL, "what removal costs")):
        sub = [c for c in cells if c["label"] in keys]
        rs, surv, stop, thr = H.holm(sub)
        nsig = sum(1 for c in sub if c["sig"])
        fam_summary.append((nm, len(sub), nsig, len(surv), stop, surv))
        A("### E1%s. The **%s** family — %s (K = %d, %d t-significant, **%d survive**)"
          % ("abc"[len(fam_summary) - 1], nm, q, len(sub), nsig, len(surv)))
        A("")
        A("| # | contrast | window | body | uncorrected p | Holm threshold | survives | in declared 28? |")
        A("|---|---|---|---|---|---|---|---|")
        for i, r in enumerate(rs, 1):
            ok = i <= len(surv)
            mark = "**yes**" if ok else (
                "**no — procedure stops here**" if (stop and i == stop[0]) else "no")
            A("| %s | %s | %s | %s | %.7f | %.6f | %s | %s |"
              % (("**%d**" % i) if (stop and i == stop[0]) else str(i),
                 r["label"], r["w"], r["body"], r["p"], thr[i - 1], mark,
                 "yes" if r["declared"] else "no"))
        A("")
        if stop:
            A("Stops at rank %d on `%s` %s %s (p = %.7f against %.6f)."
              % (stop[0], stop[1]["label"], stop[1]["w"], stop[1]["body"],
                 stop[1]["p"], stop[2]))
            A("")

    A("### E1d. What the split rescues, at every site and not only at the title's")
    A("")
    A("| family | K | t-significant | survivors | survivors also in the declared 28 |")
    A("|---|---|---|---|---|")
    for nm, K, nsig, ns, stop, surv in fam_summary:
        A("| %s | %d | %d | **%d** | %d |"
          % (nm, K, nsig, ns, sum(1 for r in surv if r["declared"])))
    A("| **all three** | **72** | **38** | **%d** | — |"
      % sum(x[3] for x in fam_summary))
    A("")
    A("Against **12** survivors under the single literal 72-cell family. Splitting by question "
      "raises the survivor count in every family, which is the point: the split is not a device "
      "that happens to rescue the title's cell, it is a device that rescues cells generally, and "
      "quoting it only where the title needs it was the fault.")
    A("")

    def find(sub_keys, label, w, body):
        sub = [c for c in cells if c["label"] in sub_keys]
        rs, surv, stop, thr = H.holm(sub)
        for i, r in enumerate(rs, 1):
            if r["label"] == label and r["w"] == w and r["body"] == body:
                return i, r, thr[i - 1], (i <= len(surv))
        return None

    A("**The removal family (K = 10) rescues BOTH coach withdrawal costs, which fail the "
      "literal 72.** Sec. 4.5 and Sec. 7 report both as failing; under the by-question split "
      "both pass, together with the finger `coach-withdrawn − prior-withdrawn` cell:")
    A("")
    A("| cell | literal-72 rank / threshold | verdict there | removal-family rank / threshold | verdict here |")
    A("|---|---|---|---|---|")
    rs72, surv72, stop72, thr72 = H.holm(cells)
    for label, w, body, lit_rank in (("coach abrupt − coach const", "ENDPOINT", "finger", 17),
                                     ("coach abrupt − coach const", "ENDPOINT", "elbow", None),
                                     ("coach abrupt − prior strict", "ENDPOINT", "finger", 18),
                                     ("coach abrupt − blank", "ENDPOINT", "finger", None)):
        for i, r in enumerate(rs72, 1):
            if r["label"] == label and r["w"] == w and r["body"] == body:
                lr, lt, lok = i, thr72[i - 1], i <= len(surv72)
                break
        rr, r2, rt, rok = find(H.REMOVAL, label, w, body)
        A("| `%s` %s %s (p = %.7f) | %d / %.6f | %s | %d / %.6f | %s |"
          % (label, w, body, r2["p"], lr, lt, "passes" if lok else "**fails**",
             rr, rt, "**passes**" if rok else "fails"))
    A("")
    A("**The versus-model-free family (K = 36) rescues two of the four Sec. 4.2 endpoint "
      "accuracy cells and neither of the other two.** `coach(const) − blank` ENDPOINT elbow "
      "(p = 0.0017642) and `prior − blank` (train) ENDPOINT elbow (0.0016228) pass; "
      "`prior − blank` (held-out) ENDPOINT elbow (0.0117911) and `randprior − blank` (train) "
      "elbow (0.0369356) still fail. So Sec. 4.2's flat statement that *not one endpoint "
      "accuracy claim survives Holm over the literal family* is a literal-72 statement, and "
      "under the by-question split two of them do — the prior's **train**-target cell and the "
      "coach's, not the prior's held-out cell.")
    A("")
    A("No one of the four family definitions now computed (declared 28, literal 72, the "
      "22-cell subset, the by-question split) is the uniquely defensible one, and none of them "
      "is applied at one site only.")
    A("")

    # ================================================================== E2
    A("## E2. Both long-budget series in full (n = 3, held-out, no intervals)")
    A("")
    A("The runs in `results_plateau2_{elbow,finger}` are seeds 0–2 of the main study continued "
      "past 12k. They were launched for 36,000 steps and **killed at 32,000 under load**, so no "
      "`.json` was ever written and the curves are parsed from the logs. **The data run to 32k**; "
      "every earlier quotation of these runs stopped at 30k without saying so. At 32k the "
      "`prior` arm has only seeds 0 and 1 on both bodies, so that row is n = 2 for `prior` and "
      "n = 3 for `blank`; the seed-matched n = 2 difference is given beside it.")
    A("")
    for body, unit in (("elbow", "mrad"), ("finger", "mm")):
        B, P = plateau(body)
        steps = sorted(set().union(*[set(s) for s in B + P]))
        A("**myo%s (%s).**" % (body.capitalize(), unit))
        A("")
        A("| step | blank (n) | prior (n) | **blank − prior** | seed-matched blank − prior (n) |")
        A("|---|---|---|---|---|")
        for st in steps:
            b, nb = mean_at(B, st)
            p, np_ = mean_at(P, st)
            common = [i for i in range(3) if st in B[i] and st in P[i]]
            pm = (sum(B[i][st] - P[i][st] for i in common) / len(common)) if common else None
            A("| %d | %.2f (%d) | %.2f (%d) | %+.2f | %s |"
              % (st, b, nb, p, np_, b - p,
                 ("%+.2f (%d)" % (pm, len(common))) if pm is not None else "—"))
        A("")
        diffs = {}
        for st in steps:
            b, _ = mean_at(B, st)
            p, _ = mean_at(P, st)
            diffs[st] = b - p
        late = {k: v for k, v in diffs.items() if k >= 12000}
        mx = max(late, key=lambda k: late[k])
        mn = min(late, key=lambda k: late[k])
        A("- Over 12k–32k the `blank − prior` gap runs %s."
          % ", ".join("%+.1f@%dk" % (late[k], k // 1000) for k in sorted(late)))
        A("- Its **maximum** over that stretch is **%+.1f at %dk** and its minimum **%+.1f at %dk**. "
          "Both series **oscillate**; neither shows a trend after 14k."
          % (late[mx], mx // 1000, late[mn], mn // 1000))
        blank_series = {st: mean_at(B, st)[0] for st in steps if st >= 12000}
        bmn = min(blank_series, key=lambda k: blank_series[k])
        A("- The `blank` arm's own long-budget curve over 12k–32k is %s; its **minimum is "
          "%.1f at %dk**."
          % (", ".join("%.1f@%dk" % (blank_series[k], k // 1000) for k in sorted(blank_series)),
             blank_series[bmn], bmn // 1000))
        A("")
    A("Two consequences for the paper's wording. On **finger**, `+67.5 at 30k` is the maximum "
      "of the 12k–32k stretch and is produced by a `blank` spike (112.6 at 28k → 131.0 at 30k → "
      "103.5 at 32k), not by the prior improving: the same gap is +30.4 at 24k and +43.8 at 32k. "
      "There is no widening after 14k, and \"the gap widens\" is deleted — both series get the "
      "same word, **oscillates**. On **elbow**, `34.7 at 30k` — the figure Sec. 4.2 uses to "
      "bracket the constant-coach student's 39.13 — is the **minimum** of the whole 12k–32k "
      "`blank` stretch; 26k (37.1), 28k (40.6) and 32k (36.2) bracket 39.13 more tightly and "
      "were never quoted.")
    A("")

    # ================================================================== E3
    A("## E3. The clean-teacher training curves, the terminal save, and the 12k checkpoints")
    A("")
    A("`train_teacher2.py` writes **one** checkpoint, at the end of training "
      "(`save_actor_path`), with **no model selection and no early stopping**. Both teacher "
      "curves below are the per-2k evaluation on the **8 training targets** printed by "
      "`run_reach.py` during the teacher run itself, and both are violently non-monotone. "
      "**Correction item 32's non-monotonicity audit covered the six main student arms and "
      "never covered these two runs.**")
    A("")
    for body, log in (("myoElbow (mrad)", "teacher_elbow_clean30k.log"),
                      ("myoFinger (mm)", "teacher_finger_clean30k.log")):
        c = curve(os.path.join(ROOT, log))
        steps = sorted(c)
        vals = [c[s] for s in steps]
        A("**%s** (`%s`), train-target eval per 2k:" % (body, log))
        A("")
        A("| step | " + " | ".join("%dk" % (s // 1000) for s in steps) + " |")
        A("|---" * (len(steps) + 1) + "|")
        A("| dist | " + " | ".join(
            ("**%.1f**" % v) if s == steps[-1] else "%.1f" % v
            for s, v in zip(steps, vals)) + " |")
        A("")
        lo, hi = min(vals), max(vals)
        last = vals[-1]
        A("- Range over the run: **%.1f – %.1f**, a factor of %.1f. The saved checkpoint is the "
          "**last** value, %.1f." % (lo, hi, hi / lo, last))
        if last == lo:
            A("- The terminal save happens to be the **global minimum** of the curve.")
        else:
            prev = vals[-4:-1]
            A("- The terminal save is **worse than each of the preceding three** (%s), by %.0f%% "
              "against their mean, and the run contains a %.1f spike at %dk."
              % (", ".join("%.1f" % v for v in prev),
                 100.0 * (last / (sum(prev) / len(prev)) - 1.0),
                 hi, steps[vals.index(hi)] // 1000))
        A("")
    A("**The 12k checkpoints of these same two runs exist on disk and had never been scored.** "
      "`teacher_elbow_clean12k.pt` and `teacher_finger_clean12k.pt` were written on 27 July by "
      "the same script at `--steps 12000`, seed 100, and reproduce the first six evaluation "
      "points of the 30k logs exactly (elbow 99.4 / 57.2 / 149.0 / 75.2 / 38.0 / 47.7; finger "
      "146.4 / 144.9 / 141.6 / 131.7 / 135.8 / 134.0), so they are the same trajectory. **No "
      "script in the repository references them and no eval log for them existed.** Scored now "
      "with the unmodified `teacher_eval.py`:")
    A("")
    A("| body | checkpoint | train (8 targets) | held-out (20 targets) |")
    A("|---|---|---|---|")
    for b, ck, tr, ho in TEACHER_EVAL:
        A("| %s | `%s` | %.1f | **%.1f** |" % (b, ck, tr, ho))
    A("")
    A("- On **myoElbow** the extra 18k steps help: held-out 62.6 → **27.2**.")
    A("- On **myoFinger** they **hurt**: held-out **129.4 at 12k → 169.1 at 30k**, a loss of "
      "39.7 mm from continuing to train the same seed.")
    A("- The finger teacher's status as a *near-no-op* — 169.1 against the 172.3 mm "
      "zero-activation referent, 3.2 mm — is therefore a property of **the 30k terminal "
      "checkpoint**, not of the body. The 12k checkpoint of the same run sits **42.9 mm** below "
      "the no-op referent. That does not overturn the Sec. 5 rival (the coach runs distil from "
      "the 30k checkpoint, so 169.1 is the target the students actually tracked), but it does "
      "remove \"myoFinger is a hard body\" as the only available reading of it: **within-run "
      "checkpoint variance is sufficient on its own to produce the teacher-quality gap between "
      "the two bodies.**")
    A("- All four numbers in the table are single seed-100 evaluations with no interval, the "
      "same status Sec. 4.8 gives the 27.2 and 169.1 figures.")
    A("")

    # ================================================================== E4
    A("## E4. The fourth long-budget unaided run per body")
    A("")
    A("`train_teacher2.py` calls `run(\"blank\", seed=100, total_steps=30000, …)` — model-free "
      "SAC, no body prior, no coach, 30,000 steps — and `teacher_eval.py` scores the result "
      "with `evaluate(w, fixed_eval_targets(20), randomize_pose=False)`, which is the **same "
      "function on the same 20 held-out targets** that `run_reach.py --heldout` uses. The "
      "teacher run is therefore also an **unaided long-budget baseline**, and there is one per "
      "body. Its role was single-labelled as \"the teacher\" while its data answered a second "
      "question; this is the fourth recurrence of the run-but-never-scored species.")
    A("")
    B_e, P_e = plateau("elbow")
    B_f, P_f = plateau("finger")
    A("| body | unaided run | held-out error at 30k |")
    A("|---|---|---|")
    for i in range(3):
        A("| myoElbow (mrad) | `results_plateau2_elbow` blank seed %d | %.1f |" % (i, B_e[i][30000]))
    A("| myoElbow (mrad) | `teacher_elbow_clean30k` blank seed 100 | 27.2 |")
    A("| myoElbow (mrad) | **constant-coach student at 12k (n = 12)** | **39.13** |")
    for i in range(3):
        A("| myoFinger (mm) | `results_plateau2_finger` blank seed %d | %.1f |" % (i, B_f[i][30000]))
    A("| myoFinger (mm) | `teacher_finger_clean30k` blank seed 100 | 169.1 |")
    A("| myoFinger (mm) | **constant-coach student at 12k (n = 12)** | **122.77** |")
    A("")
    ends = [B_e[i][30000] for i in range(3)] + [27.2]
    A("- **All four available unaided long-budget elbow runs end below the constant coach's "
      "39.13**: %s. The amortization reading of Sec. 4.2 is therefore positively supported by "
      "the data we have, not merely untested by them."
      % ", ".join("%.1f" % v for v in sorted(ends)))
    A("- On **myoFinger** the four runs are %s against the constant coach's 122.77: three of "
      "the four are worse, and the teacher run is the worst of them — so the elbow statement "
      "does not generalize and is made for elbow only."
      % ", ".join("%.1f" % v for v in sorted([B_f[i][30000] for i in range(3)] + [169.1])))
    A("- Every one of these is a **single terminal checkpoint of an oscillating curve** (E2, "
      "E3) at n = 1 per run, with no interval. The elbow teacher run in particular is saved at "
      "the global minimum of its own training curve.")
    A("- \"The only long-budget data we have\" was false at three sites (Sec. 4.3, Sec. 4.2, "
      "Sec. 6) and the missing runs cut **against** the coach.")
    A("")

    # ================================================================== E5
    A("## E5. Sweep register — every number the paper quotes from a series")
    A("")
    A("| quoted number | its series | position in the series | verdict |")
    A("|---|---|---|---|")
    A("| finger `blank − prior` **+67.5 @30k** (Sec. 4.8) | 12k–32k, eleven points | "
      "**series maximum** | selective; both series now printed in full, \"widens\" deleted |")
    A("| elbow `blank` **34.7 @30k** (Sec. 4.2 amortization) | 12k–32k, eleven points | "
      "**series minimum** | selective; series printed, and superseded by the four-run "
      "statement of E4 |")
    A("| elbow `blank` 51.9 @24k (Sec. 4.2) | same series | mid-series, not an extremum | clean |")
    A("| elbow teacher **27.2** held-out (Sec. 3.4, 4.1, 4.3, 5, 6) | 15-point train curve, "
      "terminal save | **saved at the global minimum** | rescoped to \"as captured\" |")
    A("| finger teacher **169.1** held-out (same sites) | 15-point train curve, terminal save | "
      "**saved at the worst of its last four**, ~30% above their mean | rescoped to \"as "
      "captured\"; 12k checkpoint scores 129.4 |")
    A("| by-question split: route family **8 of 26** (Sec. 4.9) | three parallel families | "
      "only the family containing the title was printed | all three printed (E1) |")
    A("| `coach(const) − prior` per-checkpoint −49.64 … +32.27 (Sec. 4.3) | six checkpoints | "
      "all six printed | clean |")
    A("| K-sensitivity 72 → 90 (Sec. 4.9) | seven values of K | all seven printed | clean |")
    A("| random-action referent −45.75 ± 7.21 / −50.64 ± 8.60 (Sec. 4.6, 4.8) | eight RNG "
      "seeds, two protocols | both protocols and all eight seeds printed | clean |")
    A("| elbow order-of-magnitude ratios 9.33× – 17.1× (Sec. 4.8) | nine conditions | all nine "
      "enumerated | clean |")
    A("| pre-cut `abrupt − constant` +1.65 / +1.67 / +1.27 (Sec. 3.2) | three pre-cut "
      "checkpoints × two bodies | all printed | clean |")
    A("| dispersion SD ratios (Sec. 4.6) | 18 held-out + 6 train cells | all printed in the "
      "table | clean in the **table**; the prose enumerated three of the four kept-aid cells "
      "and omitted finger `prior` 1.68 [0.54, 3.51] — repaired (Sec. 1.1 claim 5, Sec. 4.6, "
      "Fig. 5) |")
    A("| Appendix A BCa-only cells (14) | 132 contrasts | all 14 printed | clean |")
    A("| \"the only two cells … with room to spare\" (Sec. 1.1 claim 3) | six cells surviving "
      "both families, margins 10.7× / 9.6× / 8.1× / 3.9× / 2.3× / 1.12× | the named pair ranks "
      "**1st and 4th** | false superlative; corrected to match Sec. 4.4 |")
    A("")
    A("**Parallel variants found unprinted:** the two by-question families other than the "
      "route one (E1); the 12k teacher checkpoints, trained and never scored (E3); the teacher "
      "runs as unaided long-budget baselines (E4). Nothing else in the repository was found "
      "computed-but-unprinted: `results_plateau_*` duplicates `results_plateau2_*` for the "
      "steps both cover, and the seed-3 plateau runs `run_plateau2.ps1` asks for were never "
      "launched.")
    A("")
    return L


def main(argv):
    lines = render()
    print("\n".join(lines))
    if "--append" in argv:
        with open(REC_PATH, encoding="utf-8") as fh:
            existing = fh.read()
        if MARKER in existing:
            print("\n[skip] appendix already present in RECOMPUTED.md; not appending again.")
            return
        before = len(existing.splitlines())
        with open(REC_PATH, "a", encoding="utf-8") as fh:      # APPEND ONLY
            fh.write("\n".join(lines) + "\n")
        with open(REC_PATH, encoding="utf-8") as fh:
            after = len(fh.read().splitlines())
        assert after > before, "RECOMPUTED.md shrank -- restore from RECOMPUTED.GOLDEN.bak"
        print("\n[ok] appended %d lines to RECOMPUTED.md (%d -> %d)"
              % (after - before, before, after))


if __name__ == "__main__":
    main(sys.argv[1:])
